# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  security.user_provider:
    class: AppBundle\Security\UserProvider
    arguments: ["@database_connection"]

  app.exception_listener:
    class: AppBundle\Security\CsrfExceptionListener
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  model.esl:
    class: AppBundle\services\EslModel
    arguments: ["@database_connection"]
  model.player:
    class: AppBundle\services\PlayerModel
    arguments: ["@database_connection"]
